
#cmakedefine MAGNUM_IMPLOTINTEGRATION_BUILD_STATIC

#ifdef MAGNUM_IMPLOTINTEGRATION_USER_CONFIG
#include MAGNUM_IMPLOTINTEGRATION_USER_CONFIG
#endif

#define MAGNUM_IMPLOTINTEGRATION_HAS_IMPLOT_EVENT_IO (IMPLOT_VERSION_NUM >= 18700)
